### ISSUE TITLE
Reformat output of master_accession_list adapter

### ISSUE THREAD

**Issue by vivekkrish** [Gregor-Mendel-Institute/araport-athaliana-master-accession-table#1]
Hi @timeu ,

Thanks for developing this adapter. We are planning to use it to augment some aspects of the 1001 Genomes SNP tracks in our Araport JBrowse (currently under development).

As of now, for a query like so:

```
https://api.araport.org/community/v0.3/gmi/master_accession_list_v0.1.0/search?id=10001&LIMIT=1
```

The response received from this adapter is of the form:

```
{"kind": "fusiontables#sqlresponse", "rows": [["10001", "TueV-13", "GER", "Tubingen - Volksbank", 48.52, 9.05, "Kirsten Bomblies", "1999-12-30 0:00:00", "CS76407", "", "", "", "Y", "", "", "MPI"]], "columns": ["id", "name", "country", "sitename", "latitude", "longitude", "collector", "collectiondate", "CS_number", "pilot_projects", "Nordborg2005", "Nordborg2012", "Cao2011", "Schmitz2013", "Long2013", "seq_by"]}
```

Is it possible to reformulate this into a more traditional key --> value pair based JSON object, where "key" is the column name and the "value" is the column value? That would make it a bit more easier to consume the data.

```
{ "kind": "fusiontables#sqlresponse", "rows": [ { "id" : "10001", "name" : "TueV-13", "country" : "GER", ... } ] }
```

Thank you!

**Comment by timeu** [comment]
The reason why this is formatted this way, is because it is more efficient than the key/value format. 
The `list`  endpoint returns 7425 records.
With the current format the payload size is: 1.1 MB while with the key/value format it is 2.4 MB (because the column names are redundant). 

However I will add an additional parameter to the service that will convert it to the key/value format, so it is easily usuable for the JBrowse track.

**Comment by timeu** [comment]
@vivekkrish I pushed it to Adama and it is live. Just add `alt_format` to the query to ge the key/value format.

**Comment by vivekkrish** [comment]
Hi @timeu , thank you for the quick fix. I will test it out and report back here.

It definitely helps to have this option for simple queries, so that the user can easily cast the JSON string into a programming language native object and have quick access to key -> value pairs.

Thanks again!

**Comment by vivekkrish** [comment]
Hi @timeu , the API explorer was timing out, so I tested it on the command line. Here is what I see:

```
>>> import main
>>> main.search({'id':10001,'LIMIT':1,'alt_format':True})
('application/json', '{"kind": "fusiontables#sqlresponse", "rows": [{"name": "TueV-13", "Cao2011": "Y", "Schmitz2013": "", "sitename": "Tubingen - Volksbank", "country": "GER", "Long2013": "", "Nordborg2005": "", "longitude": 9.05, "pilot_projects": "", "Nordborg2012": "", "collectiondate": "1999-12-30 0:00:00", "seq_by": "MPI", "latitude": 48.52, "collector": "Kirsten Bomblies", "id": "10001", "CS_number": "CS76407"}], "columns": ["id", "name", "country", "sitename", "latitude", "longitude", "collector", "collectiondate", "CS_number", "pilot_projects", "Nordborg2005", "Nordborg2012", "Cao2011", "Schmitz2013", "Long2013", "seq_by"]}')
```

Looks good! You could exclude the columns: [] array from the return JSON when `alt_format` is `true`.

BTW, you might want to fix the metadata.yml by setting the default for `alt_format` as `false`. On the API explorer, even though you've labelled the parameter as not required, it's value seems to be defaulting to `true`.

Thank you!

**Comment by timeu** [comment]
Ok I changed it and pushed it to adama.
The timeout issue is due to the dynamic IP and firewall.

**Comment by vivekkrish** [comment]
Perfect! :+1: 

Thank you.
